name: whatsapp_bot_container
description: "WhatsApp Bot Container — Flutter + Baileys Node.js"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
  # Downgrade para compatibilidade com o Dart 3.5.0
  flutter_foreground_task: ^8.17.0
  
  wakelock_plus: ^1.4.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.4
  
  # Agora podemos usar uma versão compatível com a 8.17.0
  shared_preferences: ^2.2.3
  
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/nodejs-project/
